<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="bogon" name="script.ershouche.CheYuanXiangQingTest" tests="9" failures="1" timestamp="17 Jul 2017 09:02:51 GMT" time="1098.788" errors="0">
  <testcase name="ershouche_cheyuanxiangqing_testcase4" time="108.495" classname="script.ershouche.CheYuanXiangQingTest"/>
  <testcase name="ershouche_cheyuanxiangqing_testcase6" time="125.556" classname="script.ershouche.CheYuanXiangQingTest"/>
  <testcase name="ershouche_cheyuanxiangqing_testcase5" time="105.053" classname="script.ershouche.CheYuanXiangQingTest"/>
  <testcase name="ershouche_cheyuanxiangqing_testcase3" time="271.565" classname="script.ershouche.CheYuanXiangQingTest"/>
  <testcase name="ershouche_cheyuanxiangqing_testcase2" time="118.072" classname="script.ershouche.CheYuanXiangQingTest"/>
  <testcase name="ershouche_cheyuanxiangqing_testcase9" time="70.673" classname="script.ershouche.CheYuanXiangQingTest"/>
  <testcase name="ershouche_cheyuanxiangqing_testcase8" time="96.123" classname="script.ershouche.CheYuanXiangQingTest">
    <failure type="java.lang.AssertionError" message="检查输入手机号码成功 expected [1366666666] but found [13666666666]">
      <![CDATA[java.lang.AssertionError: 检查输入手机号码成功 expected [1366666666] but found [13666666666]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at script.ershouche.CheYuanXiangQingTest.ershouche_cheyuanxiangqing_testcase8(CheYuanXiangQingTest.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- ershouche_cheyuanxiangqing_testcase8 -->
  <testcase name="ershouche_cheyuanxiangqing_testcase1" time="153.634" classname="script.ershouche.CheYuanXiangQingTest"/>
  <testcase name="ershouche_cheyuanxiangqing_testcase7" time="49.617" classname="script.ershouche.CheYuanXiangQingTest"/>
</testsuite> <!-- script.ershouche.CheYuanXiangQingTest -->
