<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="bogon" name="script.ershouche.HomePageTest" tests="11" failures="1" timestamp="18 Jul 2017 08:30:07 GMT" time="1067.048" errors="0">
  <testcase name="ershouche_homepage_testcase4" time="165.678" classname="script.ershouche.HomePageTest"/>
  <testcase name="ershouche_homepage_testcase7" time="128.839" classname="script.ershouche.HomePageTest"/>
  <testcase name="ershouche_homepage_testcase12" time="60.951" classname="script.ershouche.HomePageTest"/>
  <testcase name="ershouche_homepage_testcase3" time="34.738" classname="script.ershouche.HomePageTest">
    <failure type="java.lang.AssertionError" message="检查进入帮买服务页面 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: 检查进入帮买服务页面 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at script.ershouche.HomePageTest.ershouche_homepage_testcase3(HomePageTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- ershouche_homepage_testcase3 -->
  <testcase name="ershouche_homepage_testcase9" time="65.769" classname="script.ershouche.HomePageTest"/>
  <testcase name="ershouche_homepage_testcase10" time="65.264" classname="script.ershouche.HomePageTest"/>
  <testcase name="ershouche_homepage_testcase6" time="173.271" classname="script.ershouche.HomePageTest"/>
  <testcase name="ershouche_homepage_testcase1" time="90.998" classname="script.ershouche.HomePageTest"/>
  <testcase name="ershouche_homepage_testcase5" time="148.791" classname="script.ershouche.HomePageTest"/>
  <testcase name="ershouche_homepage_testcase8" time="61.475" classname="script.ershouche.HomePageTest"/>
  <testcase name="ershouche_homepage_testcase11" time="71.274" classname="script.ershouche.HomePageTest"/>
</testsuite> <!-- script.ershouche.HomePageTest -->
